2025-04-28 19:43:20,802  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 1 - test desc - expected result
2025-04-28 19:43:20,803         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <built-in function print>
  args:         ('Hello', 'there', 'again')
  kwargs:       {'sep': ' blah ', 'end': ' The end.\n'}
2025-04-28 19:43:20,831         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:20,840         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29135
2025-04-28 19:43:20,847         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29135
2025-04-28 19:43:20,851         runwithtimeout._runner                 DEBUG:  R1 - Starting  29136
Hello blah there blah again The end.
2025-04-28 19:43:20,855         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29135
2025-04-28 19:43:20,855         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29135
2025-04-28 19:43:20,858         runwithtimeout._worker                 DEBUG:  W9 - exiting  29135
2025-04-28 19:43:20,862         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:20,864  demo-run_with_timeout.dotest                WARNING:  RETURNED:
None


2025-04-28 19:43:20,864  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 2 - Subprocess ping known - Return subprocess pass result
2025-04-28 19:43:20,865         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x765c56a0>
  args:         (['ping', 'yahoo.com', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-04-28 19:43:20,867         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:20,875         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29139
2025-04-28 19:43:20,882         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29139
2025-04-28 19:43:20,886         runwithtimeout._runner                 DEBUG:  R1 - Starting  29140
2025-04-28 19:43:20,905         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29139
2025-04-28 19:43:20,905         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29139
2025-04-28 19:43:20,908         runwithtimeout._worker                 DEBUG:  W9 - exiting  29139
2025-04-28 19:43:20,913         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:20,914  demo-run_with_timeout.dotest                WARNING:  RETURNED:
CompletedProcess(args=['ping', 'yahoo.com', '-c', '1'], returncode=2, stdout='', stderr='ping: yahoo.com: Temporary failure in name resolution\n')


2025-04-28 19:43:20,915  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 3 - Subprocess ping unknown - Return subprocess fail result
2025-04-28 19:43:20,915         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x765c56a0>
  args:         (['ping', 'dummyunknown.com', '-c', '1'],)
  kwargs:       {'timeout': 1, 'capture_output': True, 'text': True}
2025-04-28 19:43:20,917         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:20,925         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29144
2025-04-28 19:43:20,931         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29144
2025-04-28 19:43:20,936         runwithtimeout._runner                 DEBUG:  R1 - Starting  29145
2025-04-28 19:43:20,955         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29144
2025-04-28 19:43:20,955         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29144
2025-04-28 19:43:20,958         runwithtimeout._worker                 DEBUG:  W9 - exiting  29144
2025-04-28 19:43:20,962         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:20,964  demo-run_with_timeout.dotest                WARNING:  RETURNED:
CompletedProcess(args=['ping', 'dummyunknown.com', '-c', '1'], returncode=2, stdout='', stderr='ping: dummyunknown.com: Temporary failure in name resolution\n')


2025-04-28 19:43:20,964  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 4 - Subprocess ping known/unavailable - subprocess timeout < rwt_timeout - Exception subprocess.TimeoutExpired
2025-04-28 19:43:20,965         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  3
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x765c56a0>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 0.5, 'capture_output': True, 'text': True}
2025-04-28 19:43:20,967         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:20,975         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29149
2025-04-28 19:43:20,981         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29149
2025-04-28 19:43:20,985         runwithtimeout._runner                 DEBUG:  R1 - Starting  29150
2025-04-28 19:43:21,005         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29149
2025-04-28 19:43:21,005         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29149
2025-04-28 19:43:21,008         runwithtimeout._worker                 DEBUG:  W9 - exiting  29149
2025-04-28 19:43:21,012         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:21,014  demo-run_with_timeout.dotest                WARNING:  RETURNED:
CompletedProcess(args=['ping', 'testhostx', '-c', '1'], returncode=2, stdout='', stderr='ping: testhostx: Temporary failure in name resolution\n')


2025-04-28 19:43:21,015  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 5 - Subprocess ping known/unavailable - subprocess timeout > rwt_timeout - Exception TimeoutError
2025-04-28 19:43:21,015         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  0.5
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function run at 0x765c56a0>
  args:         (['ping', 'testhostx', '-c', '1'],)
  kwargs:       {'timeout': 3, 'capture_output': True, 'text': True}
2025-04-28 19:43:21,017         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:21,025         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29154
2025-04-28 19:43:21,031         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29154
2025-04-28 19:43:21,035         runwithtimeout._runner                 DEBUG:  R1 - Starting  29155
2025-04-28 19:43:21,054         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29154
2025-04-28 19:43:21,055         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29154
2025-04-28 19:43:21,058         runwithtimeout._worker                 DEBUG:  W9 - exiting  29154
2025-04-28 19:43:21,062         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:21,064  demo-run_with_timeout.dotest                WARNING:  RETURNED:
CompletedProcess(args=['ping', 'testhostx', '-c', '1'], returncode=2, stdout='', stderr='ping: testhostx: Temporary failure in name resolution\n')


2025-04-28 19:43:21,065  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 6 - Function took too long, killed - Exception TimeoutError, File 'FileNotTouched' not created
2025-04-28 19:43:21,065         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function test_shell_1 at 0x763a8610>
  args:         (2, '/tmp/cjnfuncs_rwt/FileNotTouched')
  kwargs:       {}
2025-04-28 19:43:21,067         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:21,075         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29159
2025-04-28 19:43:21,082         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29159
2025-04-28 19:43:21,086         runwithtimeout._runner                 DEBUG:  R1 - Starting  29160
2025-04-28 19:43:21,284         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29159
2025-04-28 19:43:21,285         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29159
2025-04-28 19:43:21,485         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29159
2025-04-28 19:43:21,486         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29159
2025-04-28 19:43:21,687         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29159
2025-04-28 19:43:21,687         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29159
2025-04-28 19:43:21,888         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29159
2025-04-28 19:43:21,889         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29159
2025-04-28 19:43:22,072         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:22,073         runwithtimeout.run_with_timeout        DEBUG:  T4 - Killing worker_p
2025-04-28 19:43:22,074         runwithtimeout.worker_int_handler      DEBUG:  WH1 - Signal 15 received  29159
2025-04-28 19:43:22,074         runwithtimeout.worker_int_handler      DEBUG:  WH2 - Sending terminate to runner_p  29159
2025-04-28 19:43:22,075         runwithtimeout.runner_int_handler      DEBUG:  RH1 - Signal 15 received 29160
2025-04-28 19:43:22,180         runwithtimeout.worker_int_handler      DEBUG:  WH4 - runner_p.is_alive? False  29159
2025-04-28 19:43:22,186  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <test_shell_1> timed out after 1 seconds


2025-04-28 19:43:22,188  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 7 - Function took too long, not killed - Exception TimeoutError, File 'FileTouched_1' created
2025-04-28 19:43:23,197  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <test_shell_1> timed out after 1 seconds


2025-04-28 19:43:23,199  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 8 - Sleep took too long - Exception TimeoutError
2025-04-28 19:43:23,200         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  2
  rwt_kill:     True
  rwt_debug:    True
  Function:     <built-in function sleep>
  args:         (10,)
  kwargs:       {}
2025-04-28 19:43:23,203         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:23,216         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29163
2025-04-28 19:43:23,226         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:23,232         runwithtimeout._runner                 DEBUG:  R1 - Starting  29164
2025-04-28 19:43:23,429         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:23,430         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:23,631         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:23,631         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:23,832         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:23,833         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:24,034         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:24,035         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:24,218  demo-run_with_timeout.test_shell_1          WARNING:  Hello there 42  29162
2025-04-28 19:43:24,236         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:24,237         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:24,438         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:24,439         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:24,640         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:24,641         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:24,842         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:24,842         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:25,043         runwithtimeout._worker                 DEBUG:  W5 - NO runner_to_worker_q msg received  29163
2025-04-28 19:43:25,044         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29163
2025-04-28 19:43:25,210         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:25,212         runwithtimeout.run_with_timeout        DEBUG:  T4 - Killing worker_p
2025-04-28 19:43:25,212         runwithtimeout.worker_int_handler      DEBUG:  WH1 - Signal 15 received  29163
2025-04-28 19:43:25,213         runwithtimeout.worker_int_handler      DEBUG:  WH2 - Sending terminate to runner_p  29163
2025-04-28 19:43:25,214         runwithtimeout.runner_int_handler      DEBUG:  RH1 - Signal 15 received 29164
2025-04-28 19:43:25,319         runwithtimeout.worker_int_handler      DEBUG:  WH4 - runner_p.is_alive? False  29163
2025-04-28 19:43:25,325  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
TimeoutError: Function <sleep> timed out after 2 seconds


2025-04-28 19:43:25,326  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 9 - Invalid rwt_timeout - Exception ValueError, File 'FileTouched_2' not created
2025-04-28 19:43:25,327  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
ValueError: rwt_timeout must be type int or float, received <abc>


2025-04-28 19:43:25,327  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 10 - Invalid rwt_kill - Exception ValueError, File 'FileTouched_3' not created
2025-04-28 19:43:25,328  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
ValueError: rwt_kill must be type bool, received <abc>


2025-04-28 19:43:25,329  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 11 - Delete non-existing file - Exception FileNotFoundError from function runtime
2025-04-28 19:43:25,329         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <bound method Path.unlink of PosixPath('/tmp/cjnfuncs_rwt/nosuchfile')>
  args:         ()
  kwargs:       {}
2025-04-28 19:43:25,332         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:25,344         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29167
2025-04-28 19:43:25,354         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29167
2025-04-28 19:43:25,360         runwithtimeout._runner                 DEBUG:  R1 - Starting  29168
2025-04-28 19:43:25,373         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29167
2025-04-28 19:43:25,374         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29167
2025-04-28 19:43:25,378         runwithtimeout._worker                 DEBUG:  W9 - exiting  29167
2025-04-28 19:43:25,384         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:25,386  demo-run_with_timeout.dotest                  ERROR:  EXCEPTION:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cjnfuncs_rwt/nosuchfile'


2025-04-28 19:43:25,388  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 12 - shutil.copy, twt_debug True- 
2025-04-28 19:43:25,389         runwithtimeout.run_with_timeout        DEBUG:  
run_with_timeout switches:
  rwt_timeout:  1
  rwt_kill:     True
  rwt_debug:    True
  Function:     <function copy at 0x7669a6a0>
  args:         (PosixPath('/tmp/cjnfuncs_rwt/t15a'), PosixPath('/tmp/cjnfuncs_rwt/t15b'))
  kwargs:       {}
2025-04-28 19:43:25,392         runwithtimeout.run_with_timeout        DEBUG:  T1 - starting worker_p
2025-04-28 19:43:25,403         runwithtimeout._worker                 DEBUG:  W1 - starting runner_p  29171
2025-04-28 19:43:25,413         runwithtimeout._worker                 DEBUG:  W3 - Check for runner_to_worker_q msg  29171
2025-04-28 19:43:25,420         runwithtimeout._runner                 DEBUG:  R1 - Starting  29172
2025-04-28 19:43:25,428         runwithtimeout._worker                 DEBUG:  W4 - runner_to_worker_q msg received  29171
2025-04-28 19:43:25,428         runwithtimeout._worker                 DEBUG:  W6 - pass up msg, runner_p.join(0.2)  29171
2025-04-28 19:43:25,431         runwithtimeout._worker                 DEBUG:  W9 - exiting  29171
2025-04-28 19:43:25,435         runwithtimeout.run_with_timeout        DEBUG:  T3 - After worker_p.join with timeout
2025-04-28 19:43:25,437  demo-run_with_timeout.dotest                WARNING:  RETURNED:
/tmp/cjnfuncs_rwt/t15b


2025-04-28 19:43:25,438  demo-run_with_timeout.dotest                WARNING:  
==============================================================================================
Test 13 - shutil.copy, rwt_debug False - 
2025-04-28 19:43:25,470  demo-run_with_timeout.dotest                WARNING:  RETURNED:
/tmp/cjnfuncs_rwt/t16b


